import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { NextUIProvider } from "@nextui-org/react";
import { MyNavbar } from "~/components/navbar";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NextUIProvider>
            <main className="bg-content1 text-foreground">
              <MyNavbar />
              <div className="container min-h-screen max-w-screen-xl">
                {children}
              </div>
            </main>
          </NextUIProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
