import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { MyNavbar } from "~/components/navbar";
import { Providers } from "../providers";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable}`}
    >
      <body>
        <TRPCReactProvider>
          <Providers>
            <>
              <MyNavbar />

              <main>
                <div className="container min-h-screen max-w-screen-xl py-12">
                  {children}
                </div>
              </main>
            </>
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
